
pipeline {
     agent any
     environment {
     DOCKERHUB_CREDENTIALS = credentials('docker-hub-nicolas')
     }

    stages {
    	    
     	stage('Build docker image') {
       	    steps{
      	        sh 'docker build -t webchat:nodealpine:$BUILD_NUMBER ./app'
     	    }
     	}
          
        stage('Push image') {
	    script{
	        echo'olá'
	    }	
	 }      
    }
}	
