pipeline {
    agent any

    stages {
        stage ('Build Image') {
           steps {
     	       script {
     		   dockerapp = docker.build("web-chat-ezops:nodealpine${env.BUILD_ID}", '-f ./app/Dockerfile ./app')
               }	
           }
        }
     
        stage ('Push Image') {
            steps {
                script {
     	     	    docker.withRegistry('https://login.docker.com/u/login', 'dockerhub') {
     	     	        dockerapp.push('latest')
     	     		dockerapp.push("nodealpine${env.BUILD_ID}")
     	     	    }		
                }
            }
        }  	
    }
}
