pipeline {
    agent any

    stages {
        stage ('Build Image') {
           steps {
	       script {
		   dockerapp = docker.build("web-chat-ezops:${env.BUILD_ID}", '-f ./app/Dockerfile ./app')

	      }	
             
           }
      
        }
    }  	
}
